# Generated by Django 6.0.4 on 2026-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('t1', 'Template1'), ('t2', 'Template2'), ('t3', 'Template3')], default='t1', max_length=10),
        ),
    ]
