# Generated by Django 6.0.4 on 2026-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_github_resume_linkedin_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
