# Generated by Django 5.2 on 2026-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_feature_expansion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
